version: "3.7"

services:
  client:
    container_name: frontend
    build:
      context: client
    ports:
      - 3000:80
  server:
    container_name: backend
    build:
      context: server
    ports:
      - 5000:5000
